Add route to get streams under a given user
streamr-app/streamr-api pull request #31
Opened 2017-02-27 23:36 UTC by maxcell

Now one can pick up a specific user's streams: `/api/v1/users/:id/streams`

2017-02-28 16:04 UTC, GregKWhite requested changes
Hey Prince, I've got some things that need to be addressed with this PR:

Technically, the tests do pass, but it's because they're not really valid tests. When testing filtering (this is _kinda_ filtering, since we're grabbing streams for a user), you'll need to include additional data to ensure that your test is actually working. This can be alleviated by adding a line like `insert_list(3, :stream)`, which will create additional streams _not_ associated with the user. If you add this line, your tests will fail. This is because the controller logic did not change.

To fix this, you'll have to do 2 things:

* Add `insert_list(3, :stream)` to your test. This will ensure that the route is doing as intended. I'd also add a test to ensure that the stream's user_id is correct as well.
* Change the controller logic to optionally filter the streams if a user exists. Something like this could work:

```elixir
# StreamController
  def index(conn, params) do
    streams = params["user_id"]
              |> filtered_streams
              |> Stream.with_users
              |> Stream.ordered
              |> Repo.paginate(params)

    render(conn, "index.json-api", data: streams)
  end

  defp filtered_streams(user_id) do
    if user_id do
      Stream.for_user(user_id)
    else
      Stream
    end
  end

# Stream
  def for_user(user_id) do
    from stream in Stream,
    where: stream.user_id == ^user_id
  end
```

Also, can you please move the test into the StreamController test since that's the actual controller being tested?

2017-02-28 23:17 UTC, maxcell commented
@GregKWhite I genuinely don't know what I was thinking when I wrote this. I appreciate you reviewing this! Like after rereading what I wrote, I am not sure why I decided to put it into the user controller. Thank you for your great feedback and input!

2017-03-03 13:41 UTC, GregKWhite approved these changes

2017-03-03 13:41 UTC, GregKWhite commented on test/controllers/stream_controller_test.exs
> +
If you remove this trailing newline, it's good to me

2017-03-05 19:15 UTC, merged