Feat/update delete streams
streamr-app/streamr-api pull request #35
Opened 2017-03-05 22:37 UTC by maxcell

Adding logic for deleting and updating streams. However, just realized I should probably also add logic to delete the line data.

2017-03-18 17:35 UTC, GregKWhite requested changes

2017-03-18 17:35 UTC, GregKWhite commented on web/controllers/stream_controller.ex
> +      |> render("show.json-api", data: Repo.preload(stream, :user))
Can you change this rendering call to `send_resp(conn, 204, "")`? We don't really need to serialize the stream if it's being deleted.

2017-03-18 17:35 UTC, GregKWhite commented on web/router.ex
> +    resources "/streams", StreamController, only: [:index, :create, :show, :update, :delete] do
Since we have all of our 5 default actions, we can remove the `only: [...]` and just have `resources "/streams", StreamController do`

2017-03-18 17:39 UTC, maxcell commented
Both of those sound good. Can't push changes yet due to no internet

2017-03-23 02:51 UTC, maxcell commented on web/controllers/stream_controller.ex
> +      |> render("show.json-api", data: Repo.preload(stream, :user))
For some reason, I tried doing this and even looked a bit into it, however, whenever I would do `conn |> send_resp(204, "")` it required it to send JSON back but even when I would change it to `conn |> put_resp_header("content-type", "application/json") |> send_resp(204, "")`, it did not like that.

However, I just changed it to doing `put_status(204) |> json("")`

2017-03-26 19:18 UTC, GregKWhite approved these changes

2017-03-26 19:28 UTC, merged