Implement user auth
streamr-app/streamr-api pull request #7
Opened 2016-11-26 23:39 UTC by GregKWhite

So, I'm still going to go through and look at style and whatnot, but this is user auth!

Adds `POST /api/v1/users/auth` endpoint. This accepts **EITHER** `email`, and `password` with `password` as the `grant_type`, **OR** `refresh_token` with `refresh_token` as the grant_type.

By default, users can have up to 20 refresh tokens. If requesting a 21st token, it will delete the user's oldest token.

Each access token is a JWT, with a lifespan of 1 hour. 

Make a request using the user's email and password to `/api/v1/users/auth` with the `password` `grant_type` to retrieve a new refresh token and access token.

Make a request using the user's refresh_token to `/api/v1/users/auth` with the `refresh_token` `grant_type` to retrieve only a new access token.

2016-11-27 18:44 UTC, maxcell commented on config/config.exs
> +  secret_key: %{"k" => "X5uaThfmNGtgdwaYJJjUFA", "kty" => "oct"},
I know this is a school project, but ideally would we be worried of having this committed?

2016-11-28 01:45 UTC, GregKWhite commented on config/config.exs
> +  secret_key: %{"k" => "X5uaThfmNGtgdwaYJJjUFA", "kty" => "oct"},
Nope. We overwrite this config in a secret production file that doesn't get checked in to version control. This is only for dev and testing.

2016-11-28 01:56 UTC, maxcell commented on config/config.exs
> +  secret_key: %{"k" => "X5uaThfmNGtgdwaYJJjUFA", "kty" => "oct"},
👍 Sounds good to me.

2016-11-28 02:45 UTC, maxcell requested changes
All looks great! I tested out everything and resolved merge conflicts on my local repo, but just gotta make sure we get back in sync. Otherwise, it is good!

2016-11-28 17:28 UTC, GregKWhite commented on config/config.exs
> +  issuer: "MyApp",
Oh, whoops! Gotta change that to `Streamr`. I'll do that then fix merge conflicts.

2016-11-28 17:35 UTC, GregKWhite commented
@maxcell Can you take one last look? I believe we're good to go now.

2016-11-28 20:19 UTC, maxcell approved these changes

2016-11-28 20:21 UTC, maxcell commented
Everything looks good! I just checked through a bunch stuff. I am gonna work through a PR to do our documentation with ExDoc but if you want to go through with that, it is all good.

2016-11-28 20:24 UTC, merged